apiVersion: v1
data:
  skrouterd.json: |-
    [
        [
            "network",
            {
                "networkId": "my-van"
            }
        ],
        [
            "connector",
            {
                "name": "my-van-connector",
                "role": "inter-network",
                "host": "192.168.124.1",
                "port": "15672"
            }
        ],
        [
            "autoLink",
            {
                "name": "inter-network-autoLink",
                "externalAddress": "_topo/my-van",
                "direction": "in",
                "connection": "my-van-connector"
            }
        ]
    ]
kind: ConfigMap
metadata:
  labels:
    internal.skupper.io/router-config-hook: ""
  name: skupper-central-management
