FROM --platform=$BUILDPLATFORM golang:1.19 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN make GOOS=$TARGETOS GOARCH=$TARGETARCH

FROM --platform=$TARGETPLATFORM registry.access.redhat.com/ubi8-minimal

RUN microdnf install openssl && microdnf clean all

WORKDIR /app
COPY --from=builder /go/src/app/test/integration/bin ./

CMD ["ls"]
