ARG GO_IMAGE_BASE_TAG=1.24
FROM --platform=$BUILDPLATFORM golang:${GO_IMAGE_BASE_TAG} AS builder

ARG TARGETARCH

RUN apt update && apt install -y jq

WORKDIR /app
WORKDIR /go/src/app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
ENV CGO_ENABLED=0

RUN go install github.com/go-delve/delve/cmd/dlv@latest

RUN go build -gcflags="-N -l" -a -o /app/kube-adaptor ./cmd/kube-adaptor


LABEL   org.opencontainers.image.title="Skupper Router Adaptor"   org.opencontainers.image.description="Kubernetes aware interface for the skupper-router"

WORKDIR /app

USER 10000

CMD ["dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--log", "exec", "/app/kube-adaptor"]
