apiVersion: v1
data:
  skrouterd.json: |-
    [
        [
            "connector",
            {
                "name": "sample",
                "role": "normal",
                "host": "localhost",
                "port": "12345"
            }
        ],
        [
            "connector",
            {
                "name": "sample2",
                "role": "normal",
                "host": "localhost",
                "port": "23456"
            }
        ]
    ]
kind: ConfigMap
metadata:
  labels:
    internal.skupper.io/router-config-hook: ""
  name: skupper-central-management
  namespace: east
