site:
  name: "west"
  router-mode: "interior"
services:
  - address: "frontend"
    protocol: "http"
    ports:
      - 8080: 8080
    dependsOn:
      - "backend"
    target:
      selectors:
        - app: "frontend"
