---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    skupper.io/proxy: http
    skupper.io/ingress-only: "true"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: web
      port: 8080
      protocol: TCP
