site:
  name: "east"
  router-mode: "edge"
services:
  - address: "backend"
    protocol: "http"
    ports:
      - 8080: 8080
    target:
      selectors:
        - app: "backend"
links:
  - credential: "east-to-west"
credentials:
  # secret is expected to be created by ACM
  - name: "east-to-west"
