site:
  name: "west"
  router-mode: "interior"
services:
  - address: "frontend"
    protocol: "http"
    ports:
      - 8080: 8080
    dependsOn:
      - "backend"
    target:
      selectors:
        - app: "frontend"
token-requests:
  # this sample expects that ACM will pick up the generated secret info
  # then populate it on the east site
  - name: "east-to-west"
    type: "internal"
